version: '3.9'

services:
  pharmaseek-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8030:8000"
    volumes:
      - .:/app
      - shared_tmp:/shared/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tally_db_1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432  # Internal Docker port
      - SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - FIRST_SUPERUSER_EMAIL=admin@pharmaseek.com
      - FIRST_SUPERUSER_PASSWORD=admin123
      - DEBUG=true
      - MINIO_ENDPOINT=192.168.1.133:8900
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=pharmaseek-docs
      - MINIO_SECURE=false
      - REDIS_URL=redis://redis:6379
      - BACKEND_CORS_ORIGINS=["http://localhost:5173", "http://192.168.1.53:5173", "http://192.168.1.145:5173"]
    depends_on:
      - redis
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - redis
      - pharmaseek-fastapi
    command: >
      sh -c "rq worker default --url $${REDIS_URL}"
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tally_db_1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432  # Internal Docker port
      - SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - FIRST_SUPERUSER_EMAIL=admin@pharmaseek.com
      - FIRST_SUPERUSER_PASSWORD=admin123
      - DEBUG=true
      - MINIO_ENDPOINT=192.168.1.133:8900
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=pharmaseek-docs
      - MINIO_SECURE=false
      - BACKEND_CORS_ORIGINS=["http://localhost:5173", "http://192.168.1.53:5173", "http://192.168.1.145:5173"]
    volumes:
      - .:/app
      - shared_tmp:/shared/tmp

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tally_db_1
    command: ["postgres", "-c", "max_connections=200", "-c", "log_connections=on"]
    ports:
      - "10300:5432"  # 👈 HostPort:ContainerPort
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/db/init-multiple-db.sql:/docker-entrypoint-initdb.d/init-multiple-db.sql

volumes:
  redis_data:
  shared_tmp:
  pgdata:

networks:
  default:
    name: project_default
