version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11  # Lightweight CircleCI Python image
    working_directory: ~/workspace

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  build_containers:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build FastAPI and Worker Containers
          command: docker compose build pharmaseek-fastapi rq-worker

  run_fastapi_check:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start FastAPI Server (smoke test)
          command: |
            docker compose up -d pharmaseek-fastapi
            sleep 10
            curl -f http://localhost:8030/docs || exit 1
      - run:
          name: Shut down containers
          command: docker compose down

workflows:
  version: 2
  build_and_validate:
    jobs:
      - checkout_code
      - build_containers:
          requires:
            - checkout_code
      - run_fastapi_check:
          requires:
            - build_containers
