version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build containers
          command: docker-compose build

      - run:
          name: Start services
          command: docker-compose up -d

      - run:
          name: List containers (debug)
          command: docker ps -a

      - run:
          name: Logs for FastAPI
          command: docker-compose logs pharmaseek-fastapi || true

      - run:
          name: Wait for FastAPI to be ready
          command: |
            for i in $(seq 1 15); do
              echo "Checking if FastAPI is up... ($i/15)"
              docker run --rm --network project_default curlimages/curl:7.88.1 \
                curl -s http://pharmaseek-fastapi:8000/docs && echo "✅ FastAPI is up!" && exit 0
              sleep 5
            done
            echo "❌ FastAPI not responding"
            exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
