version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  run_fastapi_check:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker containers
          command: docker compose build

      - run:
          name: Start Docker services
          command: docker compose up -d

      - run:
          name: Wait for FastAPI to be ready
          command: |
            echo "Using Docker network: project_default"
            for i in $(seq 1 15); do
              echo "Checking if FastAPI is up... ($i/15)"
              STATUS=$(docker run --rm --network project_default curlimages/curl:7.88.1 \
                -s -o /dev/null -w "%{http_code}" http://pharmaseek-fastapi:8000/docs)

              if [ "$STATUS" = "200" ]; then
                echo "✅ FastAPI is up and returned HTTP 200!"
                exit 0
              fi

              echo "⏳ Still waiting... Status: $STATUS"
              sleep 5
            done
            echo "❌ FastAPI did not respond with HTTP 200"
            exit 1

      - run:
          name: Show FastAPI container logs (on failure)
          when: on_fail
          command: |
            echo "--- FastAPI Container Logs ---"
            docker logs $(docker ps -aqf "name=pharmaseek-fastapi") || true

      - run:
          name: Debug Docker state (on failure)
          when: on_fail
          command: |
            echo "--- Running Containers ---"
            docker ps -a
            echo "--- Inspect FastAPI Container ---"
            docker inspect $(docker ps -aqf "name=pharmaseek-fastapi") || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_fastapi_check
