version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  run_fastapi_check:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker containers
          command: docker compose build

      - run:
          name: Start services
          command: docker compose up -d

      - run:
          name: Wait for FastAPI to start
          command: |
            for i in {1..10}; do
              echo "Checking if FastAPI is up..."
              docker run --network container:$(docker ps -qf "name=pharmaseek-fastapi") curlimages/curl:7.88.1 \
                curl -s localhost:8000/docs && echo "FastAPI is ready!" && exit 0
              echo "Waiting for FastAPI to be ready... ($i/10)"
              sleep 5
            done
            echo "❌ FastAPI not responding"
            exit 1

      - run:
          name: Show FastAPI container logs
          when: on_fail
          command: |
            echo "--- FastAPI Container Logs ---"
            docker logs $(docker ps -aqf "name=pharmaseek-fastapi") || true

      - run:
          name: Debug Docker state
          when: on_fail
          command: |
            echo "--- Running Containers ---"
            docker ps -a
            echo "--- Inspecting FastAPI container ---"
            docker inspect $(docker ps -aqf "name=pharmaseek-fastapi") || true
